name: Legacy UnityPackage Backup

on:
  # Removed the push trigger to disable automatic runs
  workflow_dispatch: # Allows manual execution only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library folder
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-MultiExport
          restore-keys: |
            Library-

      - name: Run Unity Export
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          buildMethod: MultiPackageExporter.ExportAllPackages

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TrickleCharge-LegacyPackages
          path: build/*.unitypackage