name: Publish to Private Registry

on:
  push:
    paths:
      - 'Packages/**'

jobs:
  trigger-shared-pipeline:
    uses: Trickle-Charge/TrickleCharge-Infra/.github/workflows/registry-publish.yml@main

    secrets: inherit